name: CompassTeleport
main: dktapps\AimTP\Main
version: 1.0
api: 3.10.0
load: POSTWORLD
author: dktapps
description: Teleport clicking with a compass to where your crosshair is aiming
website: https://github.com/dktapps-pm-pl/AimTP
commands:
 compasstp:
  description: "Gives the player a compass"
  usage: "/compasstp"
  permission: compass.teleport

permissions:
 compass.teleport:
  default: op
  description: "Allows the player to use /compasstp"
 compass.teleport.use:
  default: op
  description: "Allows the player to use a teleporter compass item"
